version: "3"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: docker_template_node
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./src:/src
